---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mgcsuwmt/public_html/
    - /bin/cp -r public_html/. $DEPLOYPATH
    - export DEPLOYPATH=/home/mgcsuwmt/blog/
    - /bin/cp -r blog/. $DEPLOYPATH
    - export DEPLOYPATH=/home/mgcsuwmt/resume/
    - /bin/cp -r resume/. $DEPLOYPATH