---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mgcsuwmt/public_html/
    - /bin/cp -r public/. $DEPLOYPATH
    - export DEPLOYPATH=/home/mgcsuwmt/blog/
    - /bin/cp -r blog/. $DEPLOYPATH
    - export DEPLOYPATH=/home/mgcsuwmt/general_stuff/
    - /bin/cp -r general_stuff/. $DEPLOYPATH