services:
  daffy-website:
    networks:
      - proxynet
      - monitoring
    container_name: daffy_website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 12443:12443
      - 12444:12444
    restart: unless-stopped

networks:
  proxynet:
    external: true
  monitoring:
    external: true
